version: '{build}'

branches:
  only:
    - hide    

image:
  - Visual Studio 2015

configuration: Release

skip_branch_with_pr: true
clone_depth: 1

skip_commits:
  files:
    - .travis.yml
    - .gitlab-ci.yml

init:
  - ps: Update-AppveyorBuild -Version "build-$env:APPVEYOR_BUILD_NUMBER-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"

install: git submodule update --init --recursive

build_script:
  - src\BuildAll.cmd
  - exit %errorlevel%
after_build:
  - 7z a "%APPVEYOR_BUILD_FOLDER%\%APPVEYOR_PROJECT_NAME%_%APPVEYOR_BUILD_VERSION%_Windows_x86_%CONFIGURATION%_PDBs-vs2015.zip" "%APPVEYOR_BUILD_FOLDER%\src\DebugFiles\pdb\Win32_Release\*.pdb"
  - 7z a "%APPVEYOR_BUILD_FOLDER%\%APPVEYOR_PROJECT_NAME%_%APPVEYOR_BUILD_VERSION%_Windows_x64_%CONFIGURATION%_PDBs-vs2015.zip" "%APPVEYOR_BUILD_FOLDER%\src\DebugFiles\pdb\x64_Release\*.pdb"
artifacts:
  - path: output\pkg\*\*
    name: Release
  - path: "%APPVEYOR_PROJECT_NAME%_%APPVEYOR_BUILD_VERSION%_Windows_x86_%CONFIGURATION%_PDBs-vs2015.zip"
    name: PDBs (x86)
  - path: "%APPVEYOR_PROJECT_NAME%_%APPVEYOR_BUILD_VERSION%_Windows_x64_%CONFIGURATION%_PDBs-vs2015.zip"
    name: PDBs (x64)
    
deploy:
  description: 'automatic release'
  provider: GitHub
  auth_token: $(github_token)
  on:
    APPVEYOR_REPO_TAG: true
